# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editLayout.ui',
# licensing of 'editLayout.ui' applies.
#
# Created: Thu Sep  1 16:08:23 2022
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Macro_Input_Paths(object):
    def setupUi(self, Macro_Input_Paths):
        Macro_Input_Paths.setObjectName("Macro_Input_Paths")
        Macro_Input_Paths.resize(547, 319)
        self.gridLayout = QtWidgets.QGridLayout(Macro_Input_Paths)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_get_settings = QtWidgets.QPushButton(Macro_Input_Paths)
        self.btn_get_settings.setObjectName("btn_get_settings")
        self.gridLayout.addWidget(self.btn_get_settings, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Macro_Input_Paths)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_layer = QtWidgets.QLineEdit(Macro_Input_Paths)
        self.lineEdit_layer.setObjectName("lineEdit_layer")
        self.horizontalLayout_4.addWidget(self.lineEdit_layer)
        self.btn_open_layer_stack = QtWidgets.QPushButton(Macro_Input_Paths)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_layer_stack.sizePolicy().hasHeightForWidth())
        self.btn_open_layer_stack.setSizePolicy(sizePolicy)
        self.btn_open_layer_stack.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_open_layer_stack.setMaximumSize(QtCore.QSize(85, 16777215))
        self.btn_open_layer_stack.setObjectName("btn_open_layer_stack")
        self.horizontalLayout_4.addWidget(self.btn_open_layer_stack)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Macro_Input_Paths)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_layout = QtWidgets.QLineEdit(Macro_Input_Paths)
        self.lineEdit_layout.setObjectName("lineEdit_layout")
        self.horizontalLayout_2.addWidget(self.lineEdit_layout)
        self.btn_open_layout = QtWidgets.QPushButton(Macro_Input_Paths)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_layout.sizePolicy().hasHeightForWidth())
        self.btn_open_layout.setSizePolicy(sizePolicy)
        self.btn_open_layout.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_open_layout.setMaximumSize(QtCore.QSize(85, 16777215))
        self.btn_open_layout.setObjectName("btn_open_layout")
        self.horizontalLayout_2.addWidget(self.btn_open_layout)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(Macro_Input_Paths)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit_bondwire = QtWidgets.QLineEdit(Macro_Input_Paths)
        self.lineEdit_bondwire.setObjectName("lineEdit_bondwire")
        self.horizontalLayout_6.addWidget(self.lineEdit_bondwire)
        self.btn_open_bondwire = QtWidgets.QPushButton(Macro_Input_Paths)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_bondwire.sizePolicy().hasHeightForWidth())
        self.btn_open_bondwire.setSizePolicy(sizePolicy)
        self.btn_open_bondwire.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_open_bondwire.setMaximumSize(QtCore.QSize(85, 16777215))
        self.btn_open_bondwire.setObjectName("btn_open_bondwire")
        self.horizontalLayout_6.addWidget(self.btn_open_bondwire)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Macro_Input_Paths)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.combo_reliability_constraints = QtWidgets.QComboBox(Macro_Input_Paths)
        self.combo_reliability_constraints.setObjectName("combo_reliability_constraints")
        self.combo_reliability_constraints.addItem("")
        self.combo_reliability_constraints.addItem("")
        self.combo_reliability_constraints.addItem("")
        self.horizontalLayout.addWidget(self.combo_reliability_constraints)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(420, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btn_create_project = QtWidgets.QPushButton(Macro_Input_Paths)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_create_project.sizePolicy().hasHeightForWidth())
        self.btn_create_project.setSizePolicy(sizePolicy)
        self.btn_create_project.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_create_project.setObjectName("btn_create_project")
        self.horizontalLayout_5.addWidget(self.btn_create_project)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)

        self.retranslateUi(Macro_Input_Paths)
        QtCore.QMetaObject.connectSlotsByName(Macro_Input_Paths)

    def retranslateUi(self, Macro_Input_Paths):
        Macro_Input_Paths.setWindowTitle(QtWidgets.QApplication.translate("Macro_Input_Paths", "Initial Structure and Layout", None, -1))
        self.btn_get_settings.setText(QtWidgets.QApplication.translate("Macro_Input_Paths", "Get Settings.info File", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Macro_Input_Paths", "Path to layer_stack", None, -1))
        self.btn_open_layer_stack.setText(QtWidgets.QApplication.translate("Macro_Input_Paths", "Open File", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Macro_Input_Paths", "Path to layout_script", None, -1))
        self.btn_open_layout.setText(QtWidgets.QApplication.translate("Macro_Input_Paths", "Open File", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Macro_Input_Paths", "Path to Connectivity_script", None, -1))
        self.btn_open_bondwire.setText(QtWidgets.QApplication.translate("Macro_Input_Paths", "Open File", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Macro_Input_Paths", "Reliability Constraints:", None, -1))
        self.combo_reliability_constraints.setItemText(0, QtWidgets.QApplication.translate("Macro_Input_Paths", "no constraints", None, -1))
        self.combo_reliability_constraints.setItemText(1, QtWidgets.QApplication.translate("Macro_Input_Paths", "average case", None, -1))
        self.combo_reliability_constraints.setItemText(2, QtWidgets.QApplication.translate("Macro_Input_Paths", "worst case consideration", None, -1))
        self.btn_create_project.setText(QtWidgets.QApplication.translate("Macro_Input_Paths", "Create Layout", None, -1))

