# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/electricalSetup.ui',
# licensing of 'ui/electricalSetup.ui' applies.
#
# Created: Sun Oct 10 12:10:22 2021
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 500)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.electrical_setup_2 = QtWidgets.QFrame(Dialog)
        self.electrical_setup_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.electrical_setup_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.electrical_setup_2.setObjectName("electrical_setup_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.electrical_setup_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_24 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_17.addWidget(self.label_24)
        self.combo_model_type = QtWidgets.QComboBox(self.electrical_setup_2)
        self.combo_model_type.setObjectName("combo_model_type")
        self.combo_model_type.addItem("")
        self.combo_model_type.addItem("")
        self.combo_model_type.addItem("")
        self.combo_model_type.addItem("")
        self.horizontalLayout_17.addWidget(self.combo_model_type)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_19 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.lineedit_measure_name = QtWidgets.QLineEdit(self.electrical_setup_2)
        self.lineedit_measure_name.setObjectName("lineedit_measure_name")
        self.horizontalLayout_12.addWidget(self.lineedit_measure_name)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_20 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_13.addWidget(self.label_20)
        self.combo_measure_type = QtWidgets.QComboBox(self.electrical_setup_2)
        self.combo_measure_type.setObjectName("combo_measure_type")
        self.combo_measure_type.addItem("")
        self.combo_measure_type.addItem("")
        self.combo_measure_type.addItem("")
        self.horizontalLayout_13.addWidget(self.combo_measure_type)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.electrical_setup_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_3.addWidget(self.tableWidget)
        spacerItem1 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.btn_add_device = QtWidgets.QPushButton(self.electrical_setup_2)
        self.btn_add_device.setObjectName("btn_add_device")
        self.verticalLayout.addWidget(self.btn_add_device)
        self.btn_remove_device = QtWidgets.QPushButton(self.electrical_setup_2)
        self.btn_remove_device.setObjectName("btn_remove_device")
        self.verticalLayout.addWidget(self.btn_remove_device)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_21 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_15.addWidget(self.label_21)
        self.combo_source = QtWidgets.QComboBox(self.electrical_setup_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_source.sizePolicy().hasHeightForWidth())
        self.combo_source.setSizePolicy(sizePolicy)
        self.combo_source.setObjectName("combo_source")
        self.horizontalLayout_15.addWidget(self.combo_source)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_22 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_16.addWidget(self.label_22)
        self.combo_sink = QtWidgets.QComboBox(self.electrical_setup_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_sink.sizePolicy().hasHeightForWidth())
        self.combo_sink.setSizePolicy(sizePolicy)
        self.combo_sink.setObjectName("combo_sink")
        self.horizontalLayout_16.addWidget(self.combo_sink)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_23 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_14.addWidget(self.label_23)
        self.frequency = QtWidgets.QSpinBox(self.electrical_setup_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequency.sizePolicy().hasHeightForWidth())
        self.frequency.setSizePolicy(sizePolicy)
        self.frequency.setMinimumSize(QtCore.QSize(20, 0))
        self.frequency.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frequency.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.frequency.setMaximum(1000000000)
        self.frequency.setObjectName("frequency")
        self.horizontalLayout_14.addWidget(self.frequency)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.parasitic_model_layout = QtWidgets.QHBoxLayout()
        self.parasitic_model_layout.setObjectName("parasitic_model_layout")
        self.verticalLayout_4.addLayout(self.parasitic_model_layout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.trace_textedit = QtWidgets.QLineEdit(self.electrical_setup_2)
        self.trace_textedit.setObjectName("trace_textedit")
        self.horizontalLayout_4.addWidget(self.trace_textedit)
        self.btn_open_trace = QtWidgets.QPushButton(self.electrical_setup_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_trace.sizePolicy().hasHeightForWidth())
        self.btn_open_trace.setSizePolicy(sizePolicy)
        self.btn_open_trace.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_open_trace.setMaximumSize(QtCore.QSize(85, 16777215))
        self.btn_open_trace.setObjectName("btn_open_trace")
        self.horizontalLayout_4.addWidget(self.btn_open_trace)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.parasitic_model_frame = QtWidgets.QFrame(self.electrical_setup_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parasitic_model_frame.sizePolicy().hasHeightForWidth())
        self.parasitic_model_frame.setSizePolicy(sizePolicy)
        self.parasitic_model_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.parasitic_model_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parasitic_model_frame.setObjectName("parasitic_model_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.parasitic_model_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.parasitic_model_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.parasitic_textedit = QtWidgets.QLineEdit(self.parasitic_model_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parasitic_textedit.sizePolicy().hasHeightForWidth())
        self.parasitic_textedit.setSizePolicy(sizePolicy)
        self.parasitic_textedit.setObjectName("parasitic_textedit")
        self.horizontalLayout_2.addWidget(self.parasitic_textedit)
        self.btn_open_parasitic = QtWidgets.QPushButton(self.parasitic_model_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_parasitic.sizePolicy().hasHeightForWidth())
        self.btn_open_parasitic.setSizePolicy(sizePolicy)
        self.btn_open_parasitic.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_open_parasitic.setMaximumSize(QtCore.QSize(85, 16777215))
        self.btn_open_parasitic.setObjectName("btn_open_parasitic")
        self.horizontalLayout_2.addWidget(self.btn_open_parasitic)
        self.verticalLayout_4.addWidget(self.parasitic_model_frame)
        self.verticalLayout_2.addWidget(self.electrical_setup_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btn_continue = QtWidgets.QPushButton(Dialog)
        self.btn_continue.setDefault(True)
        self.btn_continue.setFlat(False)
        self.btn_continue.setObjectName("btn_continue")
        self.horizontalLayout.addWidget(self.btn_continue)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Electrical Setup", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">Electrical Setup</span></p></body></html>", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("Dialog", "Model Type:", None, -1))
        self.combo_model_type.setItemText(0, QtWidgets.QApplication.translate("Dialog", "Loop", None, -1))
        self.combo_model_type.setItemText(1, QtWidgets.QApplication.translate("Dialog", "FastHenry", None, -1))
        self.combo_model_type.setItemText(2, QtWidgets.QApplication.translate("Dialog", "PEEC", None, -1))
        self.combo_model_type.setItemText(3, QtWidgets.QApplication.translate("Dialog", "Response Surface", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Dialog", "Measure Name:", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("Dialog", "Measure Type:", None, -1))
        self.combo_measure_type.setItemText(0, QtWidgets.QApplication.translate("Dialog", "inductance", None, -1))
        self.combo_measure_type.setItemText(1, QtWidgets.QApplication.translate("Dialog", "resistance", None, -1))
        self.combo_measure_type.setItemText(2, QtWidgets.QApplication.translate("Dialog", "capacitance", None, -1))
        self.tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Dialog", "Device", None, -1))
        self.tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Dialog", "Options", None, -1))
        self.btn_add_device.setText(QtWidgets.QApplication.translate("Dialog", "Add Device", None, -1))
        self.btn_remove_device.setText(QtWidgets.QApplication.translate("Dialog", "Remove Device", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("Dialog", "Select a source:", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("Dialog", "Select a sink:", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("Dialog", "Frequency (kHz):", None, -1))
        self.frequency.setSpecialValueText(QtWidgets.QApplication.translate("Dialog", "10000", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Path to trace_orientation", None, -1))
        self.btn_open_trace.setText(QtWidgets.QApplication.translate("Dialog", "Open File", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Path to parasitic_model", None, -1))
        self.btn_open_parasitic.setText(QtWidgets.QApplication.translate("Dialog", "Open File", None, -1))
        self.btn_continue.setText(QtWidgets.QApplication.translate("Dialog", "Continue", None, -1))

