# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NEW_UI/ui/editConstraints.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(676, 293)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.min_dimensions = QtWidgets.QWidget()
        self.min_dimensions.setObjectName("min_dimensions")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.min_dimensions)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.min_dimensions)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.min_dimensions, "")
        self.min_hor_enclosure = QtWidgets.QWidget()
        self.min_hor_enclosure.setObjectName("min_hor_enclosure")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.min_hor_enclosure)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.min_hor_enclosure)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 3, item)
        self.gridLayout_2.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.min_hor_enclosure, "")
        self.min_ver_enclosure = QtWidgets.QWidget()
        self.min_ver_enclosure.setObjectName("min_ver_enclosure")
        self.gridLayout = QtWidgets.QGridLayout(self.min_ver_enclosure)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.min_ver_enclosure)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 3, item)
        self.gridLayout.addWidget(self.tableWidget_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.min_ver_enclosure, "")
        self.min_hor_spacing = QtWidgets.QWidget()
        self.min_hor_spacing.setObjectName("min_hor_spacing")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.min_hor_spacing)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.min_hor_spacing)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 3, item)
        self.gridLayout_4.addWidget(self.tableWidget_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.min_hor_spacing, "")
        self.min_ver_spacing = QtWidgets.QWidget()
        self.min_ver_spacing.setObjectName("min_ver_spacing")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.min_ver_spacing)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.min_ver_spacing)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(4)
        self.tableWidget_5.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(3, 3, item)
        self.gridLayout_5.addWidget(self.tableWidget_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.min_ver_spacing, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_continue = QtWidgets.QPushButton(Dialog)
        self.btn_continue.setObjectName("btn_continue")
        self.horizontalLayout.addWidget(self.btn_continue)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit Constraints"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Please edit the values in the constraints.csv file, then click continue.</span></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "MinWidth"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "MinLength"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "MinHorExtension"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "MinVerExtension"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "EMPTY"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "power_trace"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "bonding wire pad"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "power_lead"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("Dialog", "3.0"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("Dialog", "3.0"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("Dialog", "3.0"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("Dialog", "3.0"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.min_dimensions), _translate("Dialog", "Min Dimensions"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "EMPTY"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "power_trace"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "bonding wire pad"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "power_lead"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "EMPTY"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "power_trace"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "bonding wire pad"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "power_lead"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(0, 3)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(1, 3)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(2, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(2, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(2, 3)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(3, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(3, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(3, 3)
        item.setText(_translate("Dialog", "1"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.min_hor_enclosure), _translate("Dialog", "Min Hor Enclosure"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "EMPTY"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "power_trace"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "bonding wire pad"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "power_lead"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "EMPTY"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "power_trace"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "bonding wire pad"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "power_lead"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(0, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(0, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(0, 3)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(1, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(1, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(1, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(1, 3)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(2, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(2, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(2, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(2, 3)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(3, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(3, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(3, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_3.item(3, 3)
        item.setText(_translate("Dialog", "1"))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.min_ver_enclosure), _translate("Dialog", "Min Ver Enclosure"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "EMPTY"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "power_trace"))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "bonding wire pad"))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "power_lead"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "EMPTY"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "power_trace"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "bonding wire pad"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "power_lead"))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        item = self.tableWidget_4.item(0, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(0, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(0, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(0, 3)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(1, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(1, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(1, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(1, 3)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(2, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(2, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(2, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(2, 3)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(3, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(3, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(3, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.item(3, 3)
        item.setText(_translate("Dialog", "1"))
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.min_hor_spacing), _translate("Dialog", "Min Hor Spacing"))
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "EMPTY"))
        item = self.tableWidget_5.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "power_trace"))
        item = self.tableWidget_5.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "bonding wire pad"))
        item = self.tableWidget_5.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "power_lead"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "EMPTY"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "power_trace"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "bonding wire pad"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "power_lead"))
        __sortingEnabled = self.tableWidget_5.isSortingEnabled()
        self.tableWidget_5.setSortingEnabled(False)
        item = self.tableWidget_5.item(0, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(0, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(0, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(0, 3)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(1, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(1, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(1, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(1, 3)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(2, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(2, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(2, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(2, 3)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(3, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(3, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(3, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_5.item(3, 3)
        item.setText(_translate("Dialog", "1"))
        self.tableWidget_5.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.min_ver_spacing), _translate("Dialog", "Min Ver Spacing"))
        self.btn_continue.setText(_translate("Dialog", "Continue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

