# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NEW_UI/ui/electricalSetup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(435, 330)
        self.electrical_setup_2 = QtWidgets.QFrame(Dialog)
        self.electrical_setup_2.setGeometry(QtCore.QRect(20, 10, 391, 291))
        self.electrical_setup_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.electrical_setup_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.electrical_setup_2.setObjectName("electrical_setup_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.electrical_setup_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_19 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        self.lineEdit = QtWidgets.QLineEdit(self.electrical_setup_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_12.addWidget(self.lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_20 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_13.addWidget(self.label_20)
        self.comboBox_5 = QtWidgets.QComboBox(self.electrical_setup_2)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_21 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_15.addWidget(self.label_21)
        self.comboBox_6 = QtWidgets.QComboBox(self.electrical_setup_2)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_15.addWidget(self.comboBox_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_22 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_16.addWidget(self.label_22)
        self.comboBox_7 = QtWidgets.QComboBox(self.electrical_setup_2)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBox_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_23 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_14.addWidget(self.label_23)
        self.spinBox_9 = QtWidgets.QSpinBox(self.electrical_setup_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_9.sizePolicy().hasHeightForWidth())
        self.spinBox_9.setSizePolicy(sizePolicy)
        self.spinBox_9.setMinimumSize(QtCore.QSize(20, 0))
        self.spinBox_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox_9.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_9.setMaximum(1000000000)
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_14.addWidget(self.spinBox_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.parasitic_textedit = QtWidgets.QLineEdit(self.electrical_setup_2)
        self.parasitic_textedit.setObjectName("parasitic_textedit")
        self.horizontalLayout_5.addWidget(self.parasitic_textedit)
        self.btn_open_parasitic = QtWidgets.QPushButton(self.electrical_setup_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_parasitic.sizePolicy().hasHeightForWidth())
        self.btn_open_parasitic.setSizePolicy(sizePolicy)
        self.btn_open_parasitic.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_open_parasitic.setMaximumSize(QtCore.QSize(85, 16777215))
        self.btn_open_parasitic.setObjectName("btn_open_parasitic")
        self.horizontalLayout_5.addWidget(self.btn_open_parasitic)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.electrical_setup_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.trace_textedit = QtWidgets.QLineEdit(self.electrical_setup_2)
        self.trace_textedit.setObjectName("trace_textedit")
        self.horizontalLayout_4.addWidget(self.trace_textedit)
        self.btn_open_trace = QtWidgets.QPushButton(self.electrical_setup_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_trace.sizePolicy().hasHeightForWidth())
        self.btn_open_trace.setSizePolicy(sizePolicy)
        self.btn_open_trace.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_open_trace.setMaximumSize(QtCore.QSize(85, 16777215))
        self.btn_open_trace.setObjectName("btn_open_trace")
        self.horizontalLayout_4.addWidget(self.btn_open_trace)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">Electrical Setup</span></p></body></html>"))
        self.label_19.setText(_translate("Dialog", "Measure Name:"))
        self.label_20.setText(_translate("Dialog", "Measure Type:"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "inductance"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "resistance"))
        self.label_21.setText(_translate("Dialog", "Select a source:"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "L1"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "L2"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "L3"))
        self.label_22.setText(_translate("Dialog", "Select a sink:"))
        self.comboBox_7.setCurrentText(_translate("Dialog", "L1"))
        self.comboBox_7.setItemText(0, _translate("Dialog", "L1"))
        self.comboBox_7.setItemText(1, _translate("Dialog", "L2"))
        self.comboBox_7.setItemText(2, _translate("Dialog", "L3"))
        self.label_23.setText(_translate("Dialog", "Frequency (kHz):"))
        self.spinBox_9.setSpecialValueText(_translate("Dialog", "100000"))
        self.label_6.setText(_translate("Dialog", "Path to parasitic_model"))
        self.btn_open_parasitic.setText(_translate("Dialog", "Open File"))
        self.label_5.setText(_translate("Dialog", "Path to trace_orientation"))
        self.btn_open_trace.setText(_translate("Dialog", "Open File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

