# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NEW_UI/ui/createLayout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Macro_Input_Paths(object):
    def setupUi(self, Macro_Input_Paths):
        Macro_Input_Paths.setObjectName("Macro_Input_Paths")
        Macro_Input_Paths.resize(531, 217)
        self.verticalLayout = QtWidgets.QVBoxLayout(Macro_Input_Paths)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Macro_Input_Paths)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(Macro_Input_Paths)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.btn_open_layout = QtWidgets.QPushButton(Macro_Input_Paths)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_layout.sizePolicy().hasHeightForWidth())
        self.btn_open_layout.setSizePolicy(sizePolicy)
        self.btn_open_layout.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_open_layout.setMaximumSize(QtCore.QSize(85, 16777215))
        self.btn_open_layout.setObjectName("btn_open_layout")
        self.horizontalLayout_2.addWidget(self.btn_open_layout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(Macro_Input_Paths)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(Macro_Input_Paths)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_6.addWidget(self.lineEdit_5)
        self.btn_open_bondwire = QtWidgets.QPushButton(Macro_Input_Paths)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_bondwire.sizePolicy().hasHeightForWidth())
        self.btn_open_bondwire.setSizePolicy(sizePolicy)
        self.btn_open_bondwire.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_open_bondwire.setMaximumSize(QtCore.QSize(85, 16777215))
        self.btn_open_bondwire.setObjectName("btn_open_bondwire")
        self.horizontalLayout_6.addWidget(self.btn_open_bondwire)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Macro_Input_Paths)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(Macro_Input_Paths)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.btn_open_layout_stack = QtWidgets.QPushButton(Macro_Input_Paths)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_layout_stack.sizePolicy().hasHeightForWidth())
        self.btn_open_layout_stack.setSizePolicy(sizePolicy)
        self.btn_open_layout_stack.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_open_layout_stack.setMaximumSize(QtCore.QSize(85, 16777215))
        self.btn_open_layout_stack.setObjectName("btn_open_layout_stack")
        self.horizontalLayout_4.addWidget(self.btn_open_layout_stack)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.btn_create_project = QtWidgets.QPushButton(Macro_Input_Paths)
        self.btn_create_project.setObjectName("btn_create_project")
        self.horizontalLayout_5.addWidget(self.btn_create_project)
        self.btn_cancel = QtWidgets.QPushButton(Macro_Input_Paths)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_5.addWidget(self.btn_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Macro_Input_Paths)
        QtCore.QMetaObject.connectSlotsByName(Macro_Input_Paths)

    def retranslateUi(self, Macro_Input_Paths):
        _translate = QtCore.QCoreApplication.translate
        Macro_Input_Paths.setWindowTitle(_translate("Macro_Input_Paths", "Input Macro Paths"))
        self.label_2.setText(_translate("Macro_Input_Paths", "Path to layout_script"))
        self.btn_open_layout.setText(_translate("Macro_Input_Paths", "Open File"))
        self.label_5.setText(_translate("Macro_Input_Paths", "Path to bondwire_setup"))
        self.btn_open_bondwire.setText(_translate("Macro_Input_Paths", "Open File"))
        self.label_4.setText(_translate("Macro_Input_Paths", "Path to layer_stack"))
        self.btn_open_layout_stack.setText(_translate("Macro_Input_Paths", "Open File"))
        self.btn_create_project.setText(_translate("Macro_Input_Paths", "Create Layout"))
        self.btn_cancel.setText(_translate("Macro_Input_Paths", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Macro_Input_Paths = QtWidgets.QDialog()
    ui = Ui_Macro_Input_Paths()
    ui.setupUi(Macro_Input_Paths)
    Macro_Input_Paths.show()
    sys.exit(app.exec_())

