# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NEW_UI/ui/optimizationSetupCombined.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(417, 316)
        self.run_options = QtWidgets.QFrame(Dialog)
        self.run_options.setGeometry(QtCore.QRect(30, 20, 341, 106))
        self.run_options.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.run_options.setFrameShadow(QtWidgets.QFrame.Raised)
        self.run_options.setObjectName("run_options")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.run_options)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.run_options)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.option_1 = QtWidgets.QRadioButton(self.run_options)
        self.option_1.setObjectName("option_1")
        self.verticalLayout_5.addWidget(self.option_1)
        self.option_2 = QtWidgets.QRadioButton(self.run_options)
        self.option_2.setObjectName("option_2")
        self.verticalLayout_5.addWidget(self.option_2)
        self.option_3 = QtWidgets.QRadioButton(self.run_options)
        self.option_3.setObjectName("option_3")
        self.verticalLayout_5.addWidget(self.option_3)
        self.layout_generation_setup = QtWidgets.QFrame(Dialog)
        self.layout_generation_setup.setGeometry(QtCore.QRect(30, 30, 361, 181))
        self.layout_generation_setup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.layout_generation_setup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.layout_generation_setup.setObjectName("layout_generation_setup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layout_generation_setup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.layout_generation_setup)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layout_generation_setup)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.layout_generation_setup)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layout_generation_setup)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layout_generation_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        self.spinBox_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_2.setMaximum(999)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_3.addWidget(self.spinBox_2)
        self.label_5 = QtWidgets.QLabel(self.layout_generation_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(10, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.spinBox = QtWidgets.QSpinBox(self.layout_generation_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox.setMaximum(999)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layout_generation_setup)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layout_generation_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_3.sizePolicy().hasHeightForWidth())
        self.spinBox_3.setSizePolicy(sizePolicy)
        self.spinBox_3.setMinimumSize(QtCore.QSize(15, 0))
        self.spinBox_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_3.setMaximum(9999)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_4.addWidget(self.spinBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layout_generation_setup)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.spinBox_4 = QtWidgets.QSpinBox(self.layout_generation_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_4.sizePolicy().hasHeightForWidth())
        self.spinBox_4.setSizePolicy(sizePolicy)
        self.spinBox_4.setMinimumSize(QtCore.QSize(15, 0))
        self.spinBox_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_4.setMaximum(999)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_5.addWidget(self.spinBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.layout_generation_setup)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.comboBox_2 = QtWidgets.QComboBox(self.layout_generation_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.back_btn = QtWidgets.QPushButton(Dialog)
        self.back_btn.setGeometry(QtCore.QRect(230, 270, 75, 23))
        self.back_btn.setObjectName("back_btn")
        self.next_btn = QtWidgets.QPushButton(Dialog)
        self.next_btn.setGeometry(QtCore.QRect(320, 270, 75, 23))
        self.next_btn.setDefault(True)
        self.next_btn.setObjectName("next_btn")
        self.performance_selector = QtWidgets.QFrame(Dialog)
        self.performance_selector.setGeometry(QtCore.QRect(40, 20, 361, 81))
        self.performance_selector.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.performance_selector.setFrameShadow(QtWidgets.QFrame.Raised)
        self.performance_selector.setObjectName("performance_selector")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.performance_selector)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_18 = QtWidgets.QLabel(self.performance_selector)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_7.addWidget(self.label_18)
        self.activate_electrical_2 = QtWidgets.QCheckBox(self.performance_selector)
        self.activate_electrical_2.setObjectName("activate_electrical_2")
        self.verticalLayout_7.addWidget(self.activate_electrical_2)
        self.activate_thermal_2 = QtWidgets.QCheckBox(self.performance_selector)
        self.activate_thermal_2.setObjectName("activate_thermal_2")
        self.verticalLayout_7.addWidget(self.activate_thermal_2)
        self.electrical_setup = QtWidgets.QFrame(Dialog)
        self.electrical_setup.setGeometry(QtCore.QRect(30, 10, 361, 231))
        self.electrical_setup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.electrical_setup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.electrical_setup.setObjectName("electrical_setup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.electrical_setup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.electrical_setup)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_19 = QtWidgets.QLabel(self.electrical_setup)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_11.addWidget(self.label_19)
        self.lineEdit = QtWidgets.QLineEdit(self.electrical_setup)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_11.addWidget(self.lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.electrical_setup)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.comboBox_3 = QtWidgets.QComboBox(self.electrical_setup)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_14 = QtWidgets.QLabel(self.electrical_setup)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14)
        self.comboBox_5 = QtWidgets.QComboBox(self.electrical_setup)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_15.addWidget(self.comboBox_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.electrical_setup)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        self.comboBox_6 = QtWidgets.QComboBox(self.electrical_setup)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBox_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.electrical_setup)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.spinBox_8 = QtWidgets.QSpinBox(self.electrical_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_8.sizePolicy().hasHeightForWidth())
        self.spinBox_8.setSizePolicy(sizePolicy)
        self.spinBox_8.setMinimumSize(QtCore.QSize(20, 0))
        self.spinBox_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox_8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_8.setMaximum(1000000000)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_9.addWidget(self.spinBox_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.thermal_setup = QtWidgets.QFrame(Dialog)
        self.thermal_setup.setGeometry(QtCore.QRect(30, 20, 351, 231))
        self.thermal_setup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thermal_setup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.thermal_setup.setObjectName("thermal_setup")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.thermal_setup)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.thermal_setup)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.thermal_setup)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.comboBox_4 = QtWidgets.QComboBox(self.thermal_setup)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_20 = QtWidgets.QLabel(self.thermal_setup)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_12.addWidget(self.label_20)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.thermal_setup)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_12.addWidget(self.lineEdit_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_21 = QtWidgets.QLabel(self.thermal_setup)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_13.addWidget(self.label_21)
        self.spinBox_10 = QtWidgets.QSpinBox(self.thermal_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_10.sizePolicy().hasHeightForWidth())
        self.spinBox_10.setSizePolicy(sizePolicy)
        self.spinBox_10.setMinimumSize(QtCore.QSize(15, 0))
        self.spinBox_10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox_10.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_10.setMaximum(100000)
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_13.addWidget(self.spinBox_10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.thermal_setup)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.spinBox_9 = QtWidgets.QSpinBox(self.thermal_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_9.sizePolicy().hasHeightForWidth())
        self.spinBox_9.setSizePolicy(sizePolicy)
        self.spinBox_9.setMinimumSize(QtCore.QSize(15, 0))
        self.spinBox_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox_9.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_9.setMaximum(100000)
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_10.addWidget(self.spinBox_9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">How would you like to run PowerSynth?</span></p></body></html>"))
        self.option_1.setText(_translate("Dialog", "Layout solution generation only"))
        self.option_2.setText(_translate("Dialog", "Initial layout evaluation"))
        self.option_3.setText(_translate("Dialog", "Layout optimization/evaluation"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Layout Generation Setup:</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Layout_Mode:"))
        self.comboBox.setItemText(0, _translate("Dialog", "minimum-sized solutions"))
        self.comboBox.setItemText(1, _translate("Dialog", "variable-sized solutions"))
        self.comboBox.setItemText(2, _translate("Dialog", "fixed-sized solutions"))
        self.label_4.setText(_translate("Dialog", "Floor Plan:"))
        self.label_5.setText(_translate("Dialog", "by"))
        self.label_6.setText(_translate("Dialog", "Number of layouts:"))
        self.spinBox_3.setSpecialValueText(_translate("Dialog", "25"))
        self.label_7.setText(_translate("Dialog", "Seed:"))
        self.spinBox_4.setSpecialValueText(_translate("Dialog", "10"))
        self.label_8.setText(_translate("Dialog", "Optimization Algorithm:"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "NG-RANDOM"))
        self.back_btn.setText(_translate("Dialog", "Back"))
        self.next_btn.setText(_translate("Dialog", "Next"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Test for electrical and/or thermal performance?</span></p></body></html>"))
        self.activate_electrical_2.setText(_translate("Dialog", "Electrical Performance"))
        self.activate_thermal_2.setText(_translate("Dialog", "Thermal Performance"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">Electrical Setup</span></p></body></html>"))
        self.label_19.setText(_translate("Dialog", "Measure Name:"))
        self.label_11.setText(_translate("Dialog", "Measure Type:"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "inductance"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "resistance"))
        self.label_14.setText(_translate("Dialog", "Select a source:"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "L1"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "L2"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "L3"))
        self.label_17.setText(_translate("Dialog", "Select a sink:"))
        self.comboBox_6.setCurrentText(_translate("Dialog", "L2"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "L1"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "L2"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "L3"))
        self.label_15.setText(_translate("Dialog", "Frequency (kHz):"))
        self.spinBox_8.setSpecialValueText(_translate("Dialog", "100000"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">Thermal Setup</span></p></body></html>"))
        self.label_13.setText(_translate("Dialog", "Model Select:"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "TSFM"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "Analytical"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "ParaPower"))
        self.label_20.setText(_translate("Dialog", "Measure Name:"))
        self.label_21.setText(_translate("Dialog", "Heat Convection:"))
        self.spinBox_10.setSpecialValueText(_translate("Dialog", "1000"))
        self.label_16.setText(_translate("Dialog", "Ambient Temperature:"))
        self.spinBox_9.setSpecialValueText(_translate("Dialog", "300"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

