# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'solution_Browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_solutionBrowser(object):
    def setupUi(self, CornerStitch_Dialog):
        CornerStitch_Dialog.setObjectName("CornerStitch_Dialog")
        CornerStitch_Dialog.resize(1195, 820)
        self.gridLayout_7 = QtWidgets.QGridLayout(CornerStitch_Dialog)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.grbox_view = QtWidgets.QGroupBox(CornerStitch_Dialog)
        self.grbox_view.setMinimumSize(QtCore.QSize(600, 600))
        self.grbox_view.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.grbox_view.setObjectName("grbox_view")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.grbox_view)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.grbox_view)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.grview_layout_sols = QtWidgets.QGraphicsView(self.groupBox_4)
        self.grview_layout_sols.setObjectName("grview_layout_sols")
        self.gridLayout_6.addWidget(self.grview_layout_sols, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.grbox_view)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.grview_init_layout = QtWidgets.QGraphicsView(self.groupBox_5)
        self.grview_init_layout.setObjectName("grview_init_layout")
        self.gridLayout_8.addWidget(self.grview_init_layout, 0, 0, 1, 1)
        self.Node_ID = QtWidgets.QLabel(self.groupBox_5)
        self.Node_ID.setObjectName("Node_ID")
        self.gridLayout_8.addWidget(self.Node_ID, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.grbox_view, 0, 0, 3, 1)
        self.grbox_modes = QtWidgets.QGroupBox(CornerStitch_Dialog)
        self.grbox_modes.setMaximumSize(QtCore.QSize(16777215, 50))
        self.grbox_modes.setObjectName("grbox_modes")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.grbox_modes)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cmb_modes = QtWidgets.QComboBox(self.grbox_modes)
        self.cmb_modes.setObjectName("cmb_modes")
        self.cmb_modes.addItem("")
        self.cmb_modes.addItem("")
        self.cmb_modes.addItem("")
        self.cmb_modes.addItem("")
        self.gridLayout_5.addWidget(self.cmb_modes, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.grbox_modes, 0, 1, 1, 1)
        self.grbox_flsize = QtWidgets.QGroupBox(CornerStitch_Dialog)
        self.grbox_flsize.setMaximumSize(QtCore.QSize(16777215, 100))
        self.grbox_flsize.setObjectName("grbox_flsize")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grbox_flsize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_width = QtWidgets.QLabel(self.grbox_flsize)
        self.lbl_width.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_width.setMaximumSize(QtCore.QSize(100, 100))
        self.lbl_width.setObjectName("lbl_width")
        self.gridLayout_2.addWidget(self.lbl_width, 0, 0, 1, 1)
        self.txt_width = QtWidgets.QLineEdit(self.grbox_flsize)
        self.txt_width.setObjectName("txt_width")
        self.gridLayout_2.addWidget(self.txt_width, 0, 1, 1, 1)
        self.lbl_height_2 = QtWidgets.QLabel(self.grbox_flsize)
        self.lbl_height_2.setObjectName("lbl_height_2")
        self.gridLayout_2.addWidget(self.lbl_height_2, 0, 2, 1, 1)
        self.txt_height = QtWidgets.QLineEdit(self.grbox_flsize)
        self.txt_height.setObjectName("txt_height")
        self.gridLayout_2.addWidget(self.txt_height, 0, 3, 1, 1)
        self.gridLayout_7.addWidget(self.grbox_flsize, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(CornerStitch_Dialog)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_num_layouts = QtWidgets.QLabel(self.groupBox)
        self.lbl_num_layouts.setMaximumSize(QtCore.QSize(100, 100))
        self.lbl_num_layouts.setObjectName("lbl_num_layouts")
        self.gridLayout_3.addWidget(self.lbl_num_layouts, 0, 0, 1, 1)
        self.txt_num_layouts = QtWidgets.QLineEdit(self.groupBox)
        self.txt_num_layouts.setObjectName("txt_num_layouts")
        self.gridLayout_3.addWidget(self.txt_num_layouts, 0, 1, 1, 1)
        self.txt_num_layouts.raise_()
        self.lbl_num_layouts.raise_()
        self.gridLayout_7.addWidget(self.groupBox, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(CornerStitch_Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_fixed_locs = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_fixed_locs.setObjectName("btn_fixed_locs")
        self.gridLayout.addWidget(self.btn_fixed_locs, 0, 0, 1, 1)
        self.btn_constraints = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_constraints.setObjectName("btn_constraints")
        self.gridLayout.addWidget(self.btn_constraints, 0, 1, 1, 1)
        self.btn_eval_setup = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_eval_setup.setObjectName("btn_eval_setup")
        self.gridLayout.addWidget(self.btn_eval_setup, 1, 0, 1, 1)
        self.btn_gen_layouts = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_gen_layouts.setMinimumSize(QtCore.QSize(100, 23))
        self.btn_gen_layouts.setMaximumSize(QtCore.QSize(16777215, 23))
        self.btn_gen_layouts.setObjectName("btn_gen_layouts")
        self.gridLayout.addWidget(self.btn_gen_layouts, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 1, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(CornerStitch_Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.grview_sols_browser = QtWidgets.QGraphicsView(self.groupBox_2)
        self.grview_sols_browser.setObjectName("grview_sols_browser")
        self.gridLayout_4.addWidget(self.grview_sols_browser, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 2, 1, 1, 2)

        self.retranslateUi(CornerStitch_Dialog)
        QtCore.QMetaObject.connectSlotsByName(CornerStitch_Dialog)

    def retranslateUi(self, CornerStitch_Dialog):
        _translate = QtCore.QCoreApplication.translate
        CornerStitch_Dialog.setWindowTitle(_translate("CornerStitch_Dialog", "PowerSynth (v2.0) Layout Engine "))
        self.grbox_view.setTitle(_translate("CornerStitch_Dialog", "Layout Visualization"))
        self.groupBox_4.setTitle(_translate("CornerStitch_Dialog", "Generated Layout"))
        self.groupBox_5.setTitle(_translate("CornerStitch_Dialog", "Input (initial) Layout"))
        self.Node_ID.setText(_translate("CornerStitch_Dialog", "Node ID : "))
        self.grbox_modes.setTitle(_translate("CornerStitch_Dialog", "Modes"))
        self.cmb_modes.setItemText(0, _translate("CornerStitch_Dialog", "Minimum Size Layout"))
        self.cmb_modes.setItemText(1, _translate("CornerStitch_Dialog", "Variable Size Layout"))
        self.cmb_modes.setItemText(2, _translate("CornerStitch_Dialog", "Fixed Size Layout"))
        self.cmb_modes.setItemText(3, _translate("CornerStitch_Dialog", "Fixed Size with Fixed Locations"))
        self.grbox_flsize.setTitle(_translate("CornerStitch_Dialog", "Floorplan size"))
        self.lbl_width.setText(_translate("CornerStitch_Dialog", "Width"))
        self.lbl_height_2.setText(_translate("CornerStitch_Dialog", "Height"))
        self.groupBox.setTitle(_translate("CornerStitch_Dialog", "Layouts Solutions"))
        self.lbl_num_layouts.setText(_translate("CornerStitch_Dialog", "Num of layouts"))
        self.groupBox_3.setTitle(_translate("CornerStitch_Dialog", "Control Buttons"))
        self.btn_fixed_locs.setText(_translate("CornerStitch_Dialog", "Fixed Locations"))
        self.btn_constraints.setText(_translate("CornerStitch_Dialog", "Assign Constraints"))
        self.btn_eval_setup.setText(_translate("CornerStitch_Dialog", "Measurement Setup"))
        self.btn_gen_layouts.setText(_translate("CornerStitch_Dialog", "Generate Layouts"))
        self.groupBox_2.setTitle(_translate("CornerStitch_Dialog", "Layout Selection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CornerStitch_Dialog = QtWidgets.QDialog()
    ui = Ui_solutionBrowser()
    ui.setupUi(CornerStitch_Dialog)
    CornerStitch_Dialog.show()
    sys.exit(app.exec_())

