# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Edit_Library.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MDKWindow(object):
    def setupUi(self, MDKWindow):
        MDKWindow.setObjectName("MDKWindow")
        MDKWindow.resize(911, 580)
        self.centralwidget = QtWidgets.QWidget(MDKWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(560, 500, 75, 23))
        self.save_button.setMouseTracking(True)
        self.save_button.setObjectName("save_button")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(640, 500, 75, 23))
        self.cancel_button.setMouseTracking(True)
        self.cancel_button.setObjectName("cancel_button")
        self.cancel_button.pressed.connect(self.cancel)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 741, 491))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 711, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(15)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        self.remove_all_button = QtWidgets.QPushButton(self.tab)
        self.remove_all_button.setGeometry(QtCore.QRect(480, 430, 75, 23))
        self.remove_all_button.setMouseTracking(True)
        self.remove_all_button.setObjectName("remove_all_button")
        self.add_all_button = QtWidgets.QPushButton(self.tab)
        self.add_all_button.setGeometry(QtCore.QRect(120, 430, 75, 23))
        self.add_all_button.setMouseTracking(True)
        self.add_all_button.setObjectName("add_all_button")
        self.edit_all_button = QtWidgets.QPushButton(self.tab)
        self.edit_all_button.setGeometry(QtCore.QRect(360, 430, 75, 23))
        self.edit_all_button.setMouseTracking(True)
        self.edit_all_button.setObjectName("edit_all_button")
        self.clone_all_button = QtWidgets.QPushButton(self.tab)
        self.clone_all_button.setGeometry(QtCore.QRect(240, 430, 75, 23))
        self.clone_all_button.setObjectName("clone_all_button")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 10, 711, 411))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(11)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        self.remove_pcm_button = QtWidgets.QPushButton(self.tab_2)
        self.remove_pcm_button.setGeometry(QtCore.QRect(480, 430, 75, 23))
        self.remove_pcm_button.setMouseTracking(True)
        self.remove_pcm_button.setObjectName("remove_pcm_button")
        self.add_pcm_button = QtWidgets.QPushButton(self.tab_2)
        self.add_pcm_button.setGeometry(QtCore.QRect(120, 430, 75, 23))
        self.add_pcm_button.setMouseTracking(True)
        self.add_pcm_button.setObjectName("add_pcm_button")
        self.edit_pcm_button = QtWidgets.QPushButton(self.tab_2)
        self.edit_pcm_button.setGeometry(QtCore.QRect(360, 430, 75, 23))
        self.edit_pcm_button.setMouseTracking(True)
        self.edit_pcm_button.setObjectName("edit_pcm_button")
        self.clone_pcm_button = QtWidgets.QPushButton(self.tab_2)
        self.clone_pcm_button.setGeometry(QtCore.QRect(240, 430, 75, 23))
        self.clone_pcm_button.setMouseTracking(True)
        self.clone_pcm_button.setObjectName("clone_pcm_button")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 10, 711, 411))
        self.tableWidget_3.setAutoScroll(True)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(10)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        self.add_con_button = QtWidgets.QPushButton(self.tab_3)
        self.add_con_button.setGeometry(QtCore.QRect(120, 430, 75, 23))
        self.add_con_button.setMouseTracking(True)
        self.add_con_button.setObjectName("add_con_button")
        self.clone_con_button = QtWidgets.QPushButton(self.tab_3)
        self.clone_con_button.setGeometry(QtCore.QRect(240, 430, 75, 23))
        self.clone_con_button.setMouseTracking(True)
        self.clone_con_button.setObjectName("clone_con_button")
        self.edit_con_button = QtWidgets.QPushButton(self.tab_3)
        self.edit_con_button.setGeometry(QtCore.QRect(360, 430, 75, 23))
        self.edit_con_button.setMouseTracking(True)
        self.edit_con_button.setObjectName("edit_con_button")
        self.remove_con_button = QtWidgets.QPushButton(self.tab_3)
        self.remove_con_button.setGeometry(QtCore.QRect(480, 430, 75, 23))
        self.remove_con_button.setMouseTracking(True)
        self.remove_con_button.setObjectName("remove_con_button")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 10, 711, 411))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(10)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(9, item)
        self.remove_ins_button = QtWidgets.QPushButton(self.tab_4)
        self.remove_ins_button.setGeometry(QtCore.QRect(480, 430, 75, 23))
        self.remove_ins_button.setMouseTracking(True)
        self.remove_ins_button.setObjectName("remove_ins_button")
        self.add_ins_button = QtWidgets.QPushButton(self.tab_4)
        self.add_ins_button.setGeometry(QtCore.QRect(120, 430, 75, 23))
        self.add_ins_button.setMouseTracking(True)
        self.add_ins_button.setObjectName("add_ins_button")
        self.edit_ins_button = QtWidgets.QPushButton(self.tab_4)
        self.edit_ins_button.setGeometry(QtCore.QRect(360, 430, 75, 23))
        self.edit_ins_button.setMouseTracking(True)
        self.edit_ins_button.setObjectName("edit_ins_button")
        self.clone_ins_button = QtWidgets.QPushButton(self.tab_4)
        self.clone_ins_button.setGeometry(QtCore.QRect(240, 430, 75, 23))
        self.clone_ins_button.setMouseTracking(True)
        self.clone_ins_button.setObjectName("clone_ins_button")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_5.setGeometry(QtCore.QRect(10, 10, 711, 411))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(10)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(9, item)
        self.remove_sem_button = QtWidgets.QPushButton(self.tab_5)
        self.remove_sem_button.setGeometry(QtCore.QRect(480, 430, 75, 23))
        self.remove_sem_button.setMouseTracking(True)
        self.remove_sem_button.setObjectName("remove_sem_button")
        self.add_sem_button = QtWidgets.QPushButton(self.tab_5)
        self.add_sem_button.setGeometry(QtCore.QRect(120, 430, 75, 23))
        self.add_sem_button.setMouseTracking(True)
        self.add_sem_button.setObjectName("add_sem_button")
        self.edit_sem_button = QtWidgets.QPushButton(self.tab_5)
        self.edit_sem_button.setGeometry(QtCore.QRect(360, 430, 75, 23))
        self.edit_sem_button.setMouseTracking(True)
        self.edit_sem_button.setObjectName("edit_sem_button")
        self.clone_sem_button = QtWidgets.QPushButton(self.tab_5)
        self.clone_sem_button.setGeometry(QtCore.QRect(240, 430, 75, 23))
        self.clone_sem_button.setMouseTracking(True)
        self.clone_sem_button.setObjectName("clone_sem_button")
        self.tabWidget.addTab(self.tab_5, "")
        self.load_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_button.setGeometry(QtCore.QRect(480, 500, 75, 23))
        self.load_button.setMouseTracking(True)
        self.load_button.setObjectName("load_button")
        self.select_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_button.setGeometry(QtCore.QRect(390, 500, 75, 23))
        self.select_button.setMouseTracking(True)
        self.select_button.setObjectName("select_button")
        MDKWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MDKWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 911, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MDKWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MDKWindow)
        self.statusbar.setObjectName("statusbar")
        MDKWindow.setStatusBar(self.statusbar)
        self.dockWidget_2 = QtWidgets.QDockWidget(MDKWindow)
        self.dockWidget_2.setMinimumSize(QtCore.QSize(170, 135))
        self.dockWidget_2.setMaximumSize(QtCore.QSize(170, 500))
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(self.dockWidgetContents_2)
        self.toolBox.setObjectName("toolBox")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 152, 434))
        self.page_2.setObjectName("page_2")
        self.comboBox = QtWidgets.QComboBox(self.page_2)
        self.comboBox.setGeometry(QtCore.QRect(10, 0, 131, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.SearchItem = QtWidgets.QLineEdit(self.page_2)
        self.SearchItem.setGeometry(QtCore.QRect(10, 30, 113, 20))
        self.SearchItem.setObjectName("SearchItem")
        self.search_button = QtWidgets.QPushButton(self.page_2)
        self.search_button.setGeometry(QtCore.QRect(20, 60, 75, 23))
        self.search_button.setMouseTracking(True)
        self.search_button.setObjectName("search_button")
        self.sort_button = QtWidgets.QPushButton(self.page_2)
        self.sort_button.setGeometry(QtCore.QRect(20, 90, 75, 23))
        self.sort_button.setMouseTracking(True)
        self.sort_button.setObjectName("sort_button")
        self.toolBox.addItem(self.page_2, "")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MDKWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.actionImport = QtWidgets.QAction(MDKWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionSave = QtWidgets.QAction(MDKWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionImport_file = QtWidgets.QAction(MDKWindow)
        self.actionImport_file.setObjectName("actionImport_file")
        self.actionType_Material = QtWidgets.QAction(MDKWindow)
        self.actionType_Material.setObjectName("actionType_Material")
        self.actionImport_2 = QtWidgets.QAction(MDKWindow)
        self.actionImport_2.setObjectName("actionImport_2")
        self.actionOpen_explanation = QtWidgets.QAction(MDKWindow)
        self.actionOpen_explanation.setObjectName("actionOpen_explanation")
        self.menuFile.addAction(self.actionImport_2)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuHelp.addAction(self.actionOpen_explanation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MDKWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MDKWindow)

    def cancel(self):
        print("Nice!")

    def retranslateUi(self, MDKWindow):
        _translate = QtCore.QCoreApplication.translate
        MDKWindow.setWindowTitle(_translate("MDKWindow", "PowerSynth MDK Window"))
        self.save_button.setToolTip(_translate("MDKWindow", "Save tables\' materials to MDK file"))
        self.save_button.setText(_translate("MDKWindow", "Save"))
        self.cancel_button.setToolTip(_translate("MDKWindow", "Close this window"))
        self.cancel_button.setText(_translate("MDKWindow", "Continue"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MDKWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MDKWindow", "Type"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MDKWindow", "Young Modulus"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MDKWindow", "Poisson\'s Ratio"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MDKWindow", "Melting Temperature"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MDKWindow", "Density(Solid)"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MDKWindow", "Density(Liquid)"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MDKWindow", "Thermal Conductivity(Solid)"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MDKWindow", "Thermal Conductivity(Liquid)"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MDKWindow", "Specific Heat Capacity (Solid)"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MDKWindow", "Specific Heat Capacity (Liquid)"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MDKWindow", "Electrical Resistivity"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MDKWindow", "Relative permittivity"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MDKWindow", "Relative Permeability"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MDKWindow", "CTE"))
        self.remove_all_button.setToolTip(_translate("MDKWindow", "Chosen material is removed from the table"))
        self.remove_all_button.setText(_translate("MDKWindow", "Remove"))
        self.add_all_button.setToolTip(_translate("MDKWindow", "Add blank line to below of the table"))
        self.add_all_button.setText(_translate("MDKWindow", "Add"))
        self.edit_all_button.setToolTip(_translate("MDKWindow", "Changed values are updated"))
        self.edit_all_button.setText(_translate("MDKWindow", "Edit"))
        self.clone_all_button.setToolTip(_translate("MDKWindow", "Make clone material and show it top of the table"))
        self.clone_all_button.setText(_translate("MDKWindow", "Clone"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MDKWindow", "ALL"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MDKWindow", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MDKWindow", "Young Modulus"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MDKWindow", "Poisson\'s Ratio"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MDKWindow", "CTE"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MDKWindow", "Melting Temperature"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MDKWindow", "Density(Solid)"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MDKWindow", "Density(Liquid)"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MDKWindow", "Thermal Conductivity (Solid)"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MDKWindow", "Thermal Conductivity (Liquid)"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MDKWindow", "Specific Heat Capacity (Solid)"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("MDKWindow", "Specific Heat Capacity (Liquid)"))
        self.remove_pcm_button.setToolTip(_translate("MDKWindow", "Chosen material is removed from the table"))
        self.remove_pcm_button.setText(_translate("MDKWindow", "Remove"))
        self.add_pcm_button.setToolTip(_translate("MDKWindow", "Add blank line to below of the table"))
        self.add_pcm_button.setText(_translate("MDKWindow", "Add"))
        self.edit_pcm_button.setToolTip(_translate("MDKWindow", "Changed values are updated"))
        self.edit_pcm_button.setText(_translate("MDKWindow", "Edit"))
        self.clone_pcm_button.setToolTip(_translate("MDKWindow", "Make clone material and show it top of the table"))
        self.clone_pcm_button.setText(_translate("MDKWindow", "Clone"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MDKWindow", "PCM"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MDKWindow", "Name"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MDKWindow", "Young Modulus"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MDKWindow", "Poisson\'s Ratio"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MDKWindow", "Density"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MDKWindow", "Thermal Conductivity"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MDKWindow", "Specific Heat Capacity"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MDKWindow", "Electrical Resistivity"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MDKWindow", "Relative Permittivity"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MDKWindow", "Relative permeability"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("MDKWindow", "CTE"))
        self.add_con_button.setToolTip(_translate("MDKWindow", "Add blank line to below of the table"))
        self.add_con_button.setText(_translate("MDKWindow", "Add"))
        self.clone_con_button.setToolTip(_translate("MDKWindow", "Make clone material and show it top of the table"))
        self.clone_con_button.setText(_translate("MDKWindow", "Clone"))
        self.edit_con_button.setToolTip(_translate("MDKWindow", "Changed values are updated"))
        self.edit_con_button.setText(_translate("MDKWindow", "Edit"))
        self.remove_con_button.setToolTip(_translate("MDKWindow", "Chosen material is removed from the table"))
        self.remove_con_button.setText(_translate("MDKWindow", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MDKWindow", "Conductor"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MDKWindow", "Name"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MDKWindow", "Young Modulus"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MDKWindow", "Poisson\'s Ratio"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MDKWindow", "Density"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MDKWindow", "Thermal Conductivity"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MDKWindow", "Specific Heat Capacity"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("MDKWindow", "Electrical Resistivity"))
        item = self.tableWidget_4.horizontalHeaderItem(7)
        item.setText(_translate("MDKWindow", "Relative Permittivity"))
        item = self.tableWidget_4.horizontalHeaderItem(8)
        item.setText(_translate("MDKWindow", "Relative Permeability"))
        item = self.tableWidget_4.horizontalHeaderItem(9)
        item.setText(_translate("MDKWindow", "CTE"))
        self.remove_ins_button.setToolTip(_translate("MDKWindow", "Chosen material is removed from the table"))
        self.remove_ins_button.setText(_translate("MDKWindow", "Remove"))
        self.add_ins_button.setToolTip(_translate("MDKWindow", "Add blank line to below of the table"))
        self.add_ins_button.setText(_translate("MDKWindow", "Add"))
        self.edit_ins_button.setToolTip(_translate("MDKWindow", "Changed values are updated"))
        self.edit_ins_button.setText(_translate("MDKWindow", "Edit"))
        self.clone_ins_button.setToolTip(_translate("MDKWindow", "Make clone material and show it top of the table"))
        self.clone_ins_button.setText(_translate("MDKWindow", "Clone"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MDKWindow", "Insulator"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MDKWindow", "Name"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MDKWindow", "Young Modulus"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MDKWindow", "Poisson\'s Ratio"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MDKWindow", "Density"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MDKWindow", "Thermal Conductivity"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MDKWindow", "Specific Heat Capacity"))
        item = self.tableWidget_5.horizontalHeaderItem(6)
        item.setText(_translate("MDKWindow", "Electrical Resistivity"))
        item = self.tableWidget_5.horizontalHeaderItem(7)
        item.setText(_translate("MDKWindow", "Relative Permittivity"))
        item = self.tableWidget_5.horizontalHeaderItem(8)
        item.setText(_translate("MDKWindow", "Relative Permeability"))
        item = self.tableWidget_5.horizontalHeaderItem(9)
        item.setText(_translate("MDKWindow", "CTE"))
        self.remove_sem_button.setToolTip(_translate("MDKWindow", "Chosen material is removed from the table"))
        self.remove_sem_button.setText(_translate("MDKWindow", "Remove"))
        self.add_sem_button.setToolTip(_translate("MDKWindow", "Add blank line to below of the table"))
        self.add_sem_button.setText(_translate("MDKWindow", "Add"))
        self.edit_sem_button.setToolTip(_translate("MDKWindow", "Changed values are updated"))
        self.edit_sem_button.setText(_translate("MDKWindow", "Edit"))
        self.clone_sem_button.setToolTip(_translate("MDKWindow", "Make clone material and show it top of the table"))
        self.clone_sem_button.setText(_translate("MDKWindow", "Clone"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MDKWindow", "Semiconductor"))
        self.load_button.setToolTip(_translate("MDKWindow", "Open MDK file and upload it to the table"))
        self.load_button.setText(_translate("MDKWindow", "Load"))
        self.select_button.setToolTip(_translate("MDKWindow", "Choose material you want to use"))
        self.select_button.setText(_translate("MDKWindow", "Select"))
        self.menuFile.setTitle(_translate("MDKWindow", "File"))
        self.menuHelp.setTitle(_translate("MDKWindow", "Help"))
        self.comboBox.setItemText(0, _translate("MDKWindow", "Name"))
        self.comboBox.setItemText(1, _translate("MDKWindow", "Young Modulus"))
        self.comboBox.setItemText(2, _translate("MDKWindow", "Poisson\'s Ratio"))
        self.comboBox.setItemText(3, _translate("MDKWindow", "Melting Temperature"))
        self.comboBox.setItemText(4, _translate("MDKWindow", "Electrical Resistivity"))
        self.comboBox.setItemText(5, _translate("MDKWindow", "Density"))
        self.comboBox.setItemText(6, _translate("MDKWindow", "Density(Solid)"))
        self.comboBox.setItemText(7, _translate("MDKWindow", "Density(Liquid)"))
        self.comboBox.setItemText(8, _translate("MDKWindow", "Specific Heat Capacity"))
        self.comboBox.setItemText(9, _translate("MDKWindow", "Specific Heat Capacity (Solid)"))
        self.comboBox.setItemText(10, _translate("MDKWindow", "Specific Heat Capacity (Liquid)"))
        self.comboBox.setItemText(11, _translate("MDKWindow", "Thermal Conductivity"))
        self.comboBox.setItemText(12, _translate("MDKWindow", "Thermal Conductivity (Solid)"))
        self.comboBox.setItemText(13, _translate("MDKWindow", "Thermal Conductivity (Liquid)"))
        self.comboBox.setItemText(14, _translate("MDKWindow", "Relative Permittivity"))
        self.comboBox.setItemText(15, _translate("MDKWindow", "Relative Permeability"))
        self.comboBox.setItemText(16, _translate("MDKWindow", "CTE"))
        self.search_button.setToolTip(_translate("MDKWindow", "Search specific material, and it show the top of the table"))
        self.search_button.setText(_translate("MDKWindow", "Search"))
        self.sort_button.setToolTip(_translate("MDKWindow", "Sort materials based on the field"))
        self.sort_button.setText(_translate("MDKWindow", "Sort"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MDKWindow", "Search Material"))
        self.actionImport.setText(_translate("MDKWindow", "Import"))
        self.actionSave.setText(_translate("MDKWindow", "Export"))
        self.actionImport_file.setText(_translate("MDKWindow", "Import File"))
        self.actionType_Material.setText(_translate("MDKWindow", "Type Material"))
        self.actionImport_2.setText(_translate("MDKWindow", "Import"))
        self.actionOpen_explanation.setText(_translate("MDKWindow", "Open explanation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MDKWindow = QtWidgets.QMainWindow()
    ui = Ui_MDKWindow()
    ui.setupUi(MDKWindow)
    MDKWindow.show()
    sys.exit(app.exec_())

