# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LayoutPlotter_up.ui',
# licensing of 'LayoutPlotter_up.ui' applies.
#
# Created: Tue Sep 14 15:02:29 2021
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_InitialLayoutPlotter(object):
    def setupUi(self, InitialLayoutPlotter):
        InitialLayoutPlotter.setObjectName("InitialLayoutPlotter")
        InitialLayoutPlotter.resize(1678, 980)
        self.gridLayout_6 = QtWidgets.QGridLayout(InitialLayoutPlotter)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btn_bondwire = QtWidgets.QPushButton(InitialLayoutPlotter)
        self.btn_bondwire.setMaximumSize(QtCore.QSize(6666, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.btn_bondwire.setFont(font)
        self.btn_bondwire.setObjectName("btn_bondwire")
        self.gridLayout_6.addWidget(self.btn_bondwire, 8, 0, 1, 1)
        self.cmb_box_select_layer_view = QtWidgets.QComboBox(InitialLayoutPlotter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.cmb_box_select_layer_view.setFont(font)
        self.cmb_box_select_layer_view.setObjectName("cmb_box_select_layer_view")
        self.gridLayout_6.addWidget(self.cmb_box_select_layer_view, 0, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(InitialLayoutPlotter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 0, 2, 1, 1)
        self.btn_generat_layout_script = QtWidgets.QPushButton(InitialLayoutPlotter)
        self.btn_generat_layout_script.setMaximumSize(QtCore.QSize(6666, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.btn_generat_layout_script.setFont(font)
        self.btn_generat_layout_script.setObjectName("btn_generat_layout_script")
        self.gridLayout_6.addWidget(self.btn_generat_layout_script, 9, 0, 1, 1)
        self.grp_layout_edit = QtWidgets.QGroupBox(InitialLayoutPlotter)
        self.grp_layout_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.grp_layout_edit.setFont(font)
        self.grp_layout_edit.setObjectName("grp_layout_edit")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.grp_layout_edit)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.btn_update_xy = QtWidgets.QPushButton(self.grp_layout_edit)
        self.btn_update_xy.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.btn_update_xy.setFont(font)
        self.btn_update_xy.setObjectName("btn_update_xy")
        self.gridLayout_7.addWidget(self.btn_update_xy, 0, 2, 1, 3)
        self.lineEdit_update_Y = QtWidgets.QLineEdit(self.grp_layout_edit)
        self.lineEdit_update_Y.setEnabled(True)
        self.lineEdit_update_Y.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_update_Y.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_update_Y.setObjectName("lineEdit_update_Y")
        self.gridLayout_7.addWidget(self.lineEdit_update_Y, 1, 4, 1, 1)
        self.lineEdit_update_Width = QtWidgets.QLineEdit(self.grp_layout_edit)
        self.lineEdit_update_Width.setEnabled(True)
        self.lineEdit_update_Width.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_update_Width.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_update_Width.setObjectName("lineEdit_update_Width")
        self.gridLayout_7.addWidget(self.lineEdit_update_Width, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.grp_layout_edit)
        self.label_15.setMinimumSize(QtCore.QSize(50, 0))
        self.label_15.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 1, 0, 1, 1)
        self.lineEdit_update_X = QtWidgets.QLineEdit(self.grp_layout_edit)
        self.lineEdit_update_X.setEnabled(True)
        self.lineEdit_update_X.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_update_X.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_update_X.setObjectName("lineEdit_update_X")
        self.gridLayout_7.addWidget(self.lineEdit_update_X, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.grp_layout_edit)
        self.label_17.setMinimumSize(QtCore.QSize(50, 0))
        self.label_17.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 1, 2, 1, 1)
        self.lineEdit_update_Height = QtWidgets.QLineEdit(self.grp_layout_edit)
        self.lineEdit_update_Height.setEnabled(True)
        self.lineEdit_update_Height.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_update_Height.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_update_Height.setObjectName("lineEdit_update_Height")
        self.gridLayout_7.addWidget(self.lineEdit_update_Height, 2, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.grp_layout_edit)
        self.label_20.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 2, 2, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.grp_layout_edit)
        self.label_19.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 2, 0, 1, 1)
        self.btn_rm_obj = QtWidgets.QPushButton(self.grp_layout_edit)
        self.btn_rm_obj.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rm_obj.sizePolicy().hasHeightForWidth())
        self.btn_rm_obj.setSizePolicy(sizePolicy)
        self.btn_rm_obj.setMaximumSize(QtCore.QSize(6666, 16777215))
        self.btn_rm_obj.setBaseSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.btn_rm_obj.setFont(font)
        self.btn_rm_obj.setObjectName("btn_rm_obj")
        self.gridLayout_7.addWidget(self.btn_rm_obj, 0, 0, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.grp_layout_edit)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 3, 0, 1, 1)
        self.lbl_currentxy = QtWidgets.QLabel(self.grp_layout_edit)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.lbl_currentxy.setFont(font)
        self.lbl_currentxy.setText("")
        self.lbl_currentxy.setObjectName("lbl_currentxy")
        self.gridLayout_7.addWidget(self.lbl_currentxy, 3, 1, 1, 4)
        self.gridLayout_6.addWidget(self.grp_layout_edit, 7, 0, 1, 1)
        self.via_connectivity_info = QtWidgets.QGroupBox(InitialLayoutPlotter)
        self.via_connectivity_info.setEnabled(False)
        self.via_connectivity_info.setMinimumSize(QtCore.QSize(0, 0))
        self.via_connectivity_info.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.via_connectivity_info.setFont(font)
        self.via_connectivity_info.setFlat(False)
        self.via_connectivity_info.setCheckable(False)
        self.via_connectivity_info.setChecked(False)
        self.via_connectivity_info.setObjectName("via_connectivity_info")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.via_connectivity_info)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_21 = QtWidgets.QLabel(self.via_connectivity_info)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 0, 0, 1, 1)
        self.cmb_box_select_layer_pair = QtWidgets.QComboBox(self.via_connectivity_info)
        self.cmb_box_select_layer_pair.setObjectName("cmb_box_select_layer_pair")
        self.gridLayout_8.addWidget(self.cmb_box_select_layer_pair, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.via_connectivity_info)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 0, 2, 1, 1)
        self.cmb_box_select_via = QtWidgets.QComboBox(self.via_connectivity_info)
        self.cmb_box_select_via.setObjectName("cmb_box_select_via")
        self.gridLayout_8.addWidget(self.cmb_box_select_via, 0, 3, 1, 1)
        self.radio_btn_via_type = QtWidgets.QRadioButton(self.via_connectivity_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_btn_via_type.setFont(font)
        self.radio_btn_via_type.setObjectName("radio_btn_via_type")
        self.gridLayout_8.addWidget(self.radio_btn_via_type, 1, 1, 1, 1)
        self.radio_btn_via_type_2 = QtWidgets.QRadioButton(self.via_connectivity_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_btn_via_type_2.setFont(font)
        self.radio_btn_via_type_2.setObjectName("radio_btn_via_type_2")
        self.gridLayout_8.addWidget(self.radio_btn_via_type_2, 1, 2, 1, 1)
        self.btn_add_via_connectivity = QtWidgets.QPushButton(self.via_connectivity_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_add_via_connectivity.setFont(font)
        self.btn_add_via_connectivity.setObjectName("btn_add_via_connectivity")
        self.gridLayout_8.addWidget(self.btn_add_via_connectivity, 1, 3, 1, 1)
        self.gridLayout_6.addWidget(self.via_connectivity_info, 5, 0, 2, 1)
        self.groupBox = QtWidgets.QGroupBox(InitialLayoutPlotter)
        self.groupBox.setMaximumSize(QtCore.QSize(500, 300))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_comp_alias = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_comp_alias.setObjectName("lineEdit_comp_alias")
        self.gridLayout_3.addWidget(self.lineEdit_comp_alias, 0, 1, 1, 1)
        self.btn_open_comp_file = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_comp_file.sizePolicy().hasHeightForWidth())
        self.btn_open_comp_file.setSizePolicy(sizePolicy)
        self.btn_open_comp_file.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_open_comp_file.setBaseSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.btn_open_comp_file.setFont(font)
        self.btn_open_comp_file.setObjectName("btn_open_comp_file")
        self.gridLayout_3.addWidget(self.btn_open_comp_file, 0, 2, 1, 1)
        self.listWidget_comp_view = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_comp_view.setObjectName("listWidget_comp_view")
        self.gridLayout_3.addWidget(self.listWidget_comp_view, 1, 0, 1, 3)
        self.grp_comp_placement = QtWidgets.QGroupBox(self.groupBox)
        self.grp_comp_placement.setObjectName("grp_comp_placement")
        self.gridLayout = QtWidgets.QGridLayout(self.grp_comp_placement)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_comp_name = QtWidgets.QLineEdit(self.grp_comp_placement)
        self.lineEdit_comp_name.setText("")
        self.lineEdit_comp_name.setObjectName("lineEdit_comp_name")
        self.gridLayout.addWidget(self.lineEdit_comp_name, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.grp_comp_placement)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.grp_comp_placement)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.grp_comp_placement)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.grp_comp_placement)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.grp_comp_placement)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_comp_W = QtWidgets.QLineEdit(self.grp_comp_placement)
        self.lineEdit_comp_W.setObjectName("lineEdit_comp_W")
        self.gridLayout.addWidget(self.lineEdit_comp_W, 1, 1, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.grp_comp_placement)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 1, 5, 1, 1)
        self.lineEdit_comp_H = QtWidgets.QLineEdit(self.grp_comp_placement)
        self.lineEdit_comp_H.setObjectName("lineEdit_comp_H")
        self.gridLayout.addWidget(self.lineEdit_comp_H, 1, 4, 1, 1)
        self.cmb_box_rotation = QtWidgets.QComboBox(self.grp_comp_placement)
        self.cmb_box_rotation.setObjectName("cmb_box_rotation")
        self.gridLayout.addWidget(self.cmb_box_rotation, 1, 6, 1, 2)
        self.btn_add_comp = QtWidgets.QPushButton(self.grp_comp_placement)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.btn_add_comp.setFont(font)
        self.btn_add_comp.setObjectName("btn_add_comp")
        self.gridLayout.addWidget(self.btn_add_comp, 0, 7, 1, 1)
        self.lineEdit_comp_X = QtWidgets.QLineEdit(self.grp_comp_placement)
        self.lineEdit_comp_X.setObjectName("lineEdit_comp_X")
        self.gridLayout.addWidget(self.lineEdit_comp_X, 0, 3, 1, 1)
        self.lineEdit_comp_Y = QtWidgets.QLineEdit(self.grp_comp_placement)
        self.lineEdit_comp_Y.setObjectName("lineEdit_comp_Y")
        self.gridLayout.addWidget(self.lineEdit_comp_Y, 0, 5, 1, 2)
        self.gridLayout_3.addWidget(self.grp_comp_placement, 2, 0, 1, 3)
        self.btn_rm_list_comp = QtWidgets.QPushButton(self.groupBox)
        self.btn_rm_list_comp.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rm_list_comp.sizePolicy().hasHeightForWidth())
        self.btn_rm_list_comp.setSizePolicy(sizePolicy)
        self.btn_rm_list_comp.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_rm_list_comp.setBaseSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.btn_rm_list_comp.setFont(font)
        self.btn_rm_list_comp.setObjectName("btn_rm_list_comp")
        self.gridLayout_3.addWidget(self.btn_rm_list_comp, 3, 0, 1, 2)
        self.gridLayout_6.addWidget(self.groupBox, 3, 0, 1, 1)
        self.LayoutView = QtWidgets.QGraphicsView(InitialLayoutPlotter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.LayoutView.setBackgroundBrush(brush)
        self.LayoutView.setObjectName("LayoutView")
        self.gridLayout_6.addWidget(self.LayoutView, 1, 2, 9, 3)
        self.groupBox_2 = QtWidgets.QGroupBox(InitialLayoutPlotter)
        self.groupBox_2.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 2)
        self.cmb_box_select_layer_draw = QtWidgets.QComboBox(self.groupBox_2)
        self.cmb_box_select_layer_draw.setObjectName("cmb_box_select_layer_draw")
        self.gridLayout_5.addWidget(self.cmb_box_select_layer_draw, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 1, 1, 1, 1)
        self.cmb_box_rout_dir = QtWidgets.QComboBox(self.groupBox_2)
        self.cmb_box_rout_dir.setObjectName("cmb_box_rout_dir")
        self.gridLayout_5.addWidget(self.cmb_box_rout_dir, 1, 2, 1, 1)
        self.btn_get_layer_stack = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.btn_get_layer_stack.setFont(font)
        self.btn_get_layer_stack.setObjectName("btn_get_layer_stack")
        self.gridLayout_5.addWidget(self.btn_get_layer_stack, 1, 3, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.lineEdit_trace_W = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_trace_W.setObjectName("lineEdit_trace_W")
        self.gridLayout_2.addWidget(self.lineEdit_trace_W, 0, 6, 1, 1)
        self.lineEdit_trace_H = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_trace_H.setObjectName("lineEdit_trace_H")
        self.gridLayout_2.addWidget(self.lineEdit_trace_H, 0, 8, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 7, 1, 1)
        self.lineEdit_trace_X = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_trace_X.setObjectName("lineEdit_trace_X")
        self.gridLayout_2.addWidget(self.lineEdit_trace_X, 0, 2, 1, 1)
        self.lineEdit_trace_Y = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_trace_Y.setObjectName("lineEdit_trace_Y")
        self.gridLayout_2.addWidget(self.lineEdit_trace_Y, 0, 4, 1, 1)
        self.btn_add_trace = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.btn_add_trace.setFont(font)
        self.btn_add_trace.setObjectName("btn_add_trace")
        self.gridLayout_2.addWidget(self.btn_add_trace, 0, 9, 1, 1)
        self.radio_btn_gate = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_btn_gate.setObjectName("radio_btn_gate")
        self.gridLayout_2.addWidget(self.radio_btn_gate, 1, 5, 1, 2)
        self.radio_btn_power = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_btn_power.setObjectName("radio_btn_power")
        self.gridLayout_2.addWidget(self.radio_btn_power, 1, 2, 1, 3)
        self.gridLayout_5.addWidget(self.groupBox_3, 2, 0, 1, 4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 4, 1, 1)
        self.lineEdit_bw_padH = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_bw_padH.setEnabled(True)
        self.lineEdit_bw_padH.setText("")
        self.lineEdit_bw_padH.setObjectName("lineEdit_bw_padH")
        self.gridLayout_4.addWidget(self.lineEdit_bw_padH, 0, 7, 1, 1)
        self.btn_add_bw_pad = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.btn_add_bw_pad.setFont(font)
        self.btn_add_bw_pad.setObjectName("btn_add_bw_pad")
        self.gridLayout_4.addWidget(self.btn_add_bw_pad, 0, 8, 1, 1)
        self.lineEdit_bw_padW = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_bw_padW.setEnabled(True)
        self.lineEdit_bw_padW.setText("")
        self.lineEdit_bw_padW.setObjectName("lineEdit_bw_padW")
        self.gridLayout_4.addWidget(self.lineEdit_bw_padW, 0, 5, 1, 1)
        self.lineEdit_bw_padY = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_bw_padY.setObjectName("lineEdit_bw_padY")
        self.gridLayout_4.addWidget(self.lineEdit_bw_padY, 0, 3, 1, 1)
        self.lineEdit_bw_padX = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_bw_padX.setObjectName("lineEdit_bw_padX")
        self.gridLayout_4.addWidget(self.lineEdit_bw_padX, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 6, 1, 1)
        self.radio_button_power_pad = QtWidgets.QRadioButton(self.groupBox_5)
        self.radio_button_power_pad.setObjectName("radio_button_power_pad")
        self.gridLayout_4.addWidget(self.radio_button_power_pad, 1, 1, 1, 1)
        self.radio_button_signal_pad = QtWidgets.QRadioButton(self.groupBox_5)
        self.radio_button_signal_pad.setObjectName("radio_button_signal_pad")
        self.gridLayout_4.addWidget(self.radio_button_signal_pad, 1, 4, 1, 2)
        self.gridLayout_5.addWidget(self.groupBox_5, 3, 0, 1, 4)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 0, 3, 1)

        self.retranslateUi(InitialLayoutPlotter)
        QtCore.QMetaObject.connectSlotsByName(InitialLayoutPlotter)

    def retranslateUi(self, InitialLayoutPlotter):
        InitialLayoutPlotter.setWindowTitle(QtWidgets.QApplication.translate("InitialLayoutPlotter", "LayoutPloter", None, -1))
        self.btn_bondwire.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Bondwire Setup", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Layout View", None, -1))
        self.btn_generat_layout_script.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Generate Layout Script", None, -1))
        self.grp_layout_edit.setTitle(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Layout Edit", None, -1))
        self.btn_update_xy.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Update Selected Item", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "X", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Y", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Height", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Width", None, -1))
        self.btn_rm_obj.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Remove Selected Items", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Object Info:", None, -1))
        self.via_connectivity_info.setTitle(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Define Inter-Layer Connectivity", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Select Layer Pair", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Select Via", None, -1))
        self.radio_btn_via_type.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Through", None, -1))
        self.radio_btn_via_type_2.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Port", None, -1))
        self.btn_add_via_connectivity.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Add", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Select Devices and Components", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Component Alias", None, -1))
        self.btn_open_comp_file.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Open Componen File", None, -1))
        self.grp_comp_placement.setTitle(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Component Placement", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Name", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "X", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Height", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Y", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Width", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Rotation", None, -1))
        self.btn_add_comp.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Add", None, -1))
        self.btn_rm_list_comp.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Remove Component from List", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Draw Layout for Each Layer", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Select a layer for drawing", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Routing Direction ", None, -1))
        self.btn_get_layer_stack.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Layer Stack File", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Trace Island", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "X", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Width", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Y", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Height", None, -1))
        self.btn_add_trace.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Add", None, -1))
        self.radio_btn_gate.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Signal Trace", None, -1))
        self.radio_btn_power.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Power Trace", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Bondwire Pad", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "X", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Width", None, -1))
        self.btn_add_bw_pad.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Add", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Y", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Height", None, -1))
        self.radio_button_power_pad.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", " Power", None, -1))
        self.radio_button_signal_pad.setText(QtWidgets.QApplication.translate("InitialLayoutPlotter", "Signal", None, -1))

